apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-ljubljana
resources:
  - cronjob.yaml
images:
  - name: parlaparser-ljubljana
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-ljubljana
    newTag: '7641c3c5d34bb291c3154241e7c4e3104628ca95'
