apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-ljubljana
resources:
  - cronjob.yaml
images:
  - name: parlaparser-ljubljana
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-ljubljana
    newTag: '57f7d096a992117ca60418370a69a27ee086acd9'
